spring:
  application:
    name: hello-spring-cloud-admin-feign

server:
  port: 9765

feign:
  hystrix:
    enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    servcieUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
management:
  metrics:
    health:
      show-details: always
    endpoints:
      web:
        exposure:
          include: ["health","info"]