spring:
  application:
    name: hello-spring-cloud-zuul
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084
server:
  port: 8769

eureka:
  client:
    servcieUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

management:
  metrics:
    health:
      show-details: always
    endpoints:
      web:
        exposure:
          include: ["health","info"]