spring:
  application:
    name: hello-spring-cloud-springadmin
  zipkin:
    base-url: http://localhost:9411


eureka:
  client:
    servcieUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

management:
  metrics:
    health:
      show-details: always
    endpoints:
      web:
        exposure:
          include: healthinfo