spring:
  application:
    name: solution-zuul

server:
  port: 8769

zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: hello-spring-cloud-admin-ribbon
    api-b:
      path: /api/b/**
      serviceId: hello-spring-cloud-admin-feign