spring:
  application:
    name: solution-eureka
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegister: false
    servcieUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  metrics:
    health:
      show-details: always
    endpoints:
      web:
        exposure:
          include: health,info